include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    argument_type_not_assignable: ignore
    generic_argument_factories: true
linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    argument_type_not_assignable: false
    generic_argument_factories: true
