name: homemakers_merchant
description: A app for HomeMakers merchant.
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ac_connectivity:
    git:
      url: 'https://github.com/prasant10050/flutter-connectivity.git'
      ref: main
  animations: ^2.0.7
  animator:
    git:
      url: 'https://github.com/prasant10050/animator-1.git'
      ref: master
  app_links: ^3.4.3
  app_runner: ^2.2.0+1
  app_settings: ^5.0.0
  async: ^2.11.0
  back_button_interceptor: ^6.0.2
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.3
  collection: ^1.17.1
  connectivity_plus: ^4.0.2
  cross_file: ^0.3.3+4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  dart_jsonwebtoken: ^2.11.0
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  faker: ^2.1.0
  file_picker: ^5.5.0
  file_saver: ^0.2.7
  file_selector: ^1.0.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  flex_color_scheme: ^7.1.2
  flex_seed_scheme: ^1.3.0
  flutter:
    sdk: flutter
  flutter_animarker: ^3.4.0-beta.1
  flutter_background_executor: ^1.0.0
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.0.4
  flutter_displaymode: ^0.6.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_libphonenumber: ^2.1.4
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_parsed_text: ^2.2.1
  flutter_platform_widgets:
    git:
      url: 'https://github.com/prasant10050/flutter_platform_widgets.git'
      ref: master
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  geocoder_buddy:
    git:
      url: 'https://github.com/prasant10050/geocoder_buddy.git'
      ref: main
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
#  google_ml_kit: ^0.16.2
  google_mlkit_language_id: ^0.8.0
  google_mlkit_text_recognition: ^0.10.0
  google_mlkit_translation: ^0.8.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hyphenatorx: ^1.5.6+2
  image: ^4.0.17
  image_fade: ^0.6.2
  image_picker: ^1.0.0
  implicitly_animated_reorderable_list_2:
    git:
      url: 'https://github.com/prasant10050/implicitly_animated_reorderable_list_2.git'
      ref: master
  intl: ^0.18.0
  isolate_manager:
    git:
      url: 'https://github.com/prasant10050/isolate_manager.git'
      ref: main
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  localstore: ^1.3.5
  location: ^5.0.3
  logger: ^2.0.1
  lottie: ^2.5.0
  moment_dart:
    git:
      url: 'https://github.com/prasant10050/moment_dart.git'
      ref: master
  multi_image_crop:
    git:
      url: 'https://github.com/prasant10050/multi_image_crop.git'
      ref: master
  network_manager:
    git:
      url: 'git@bitbucket.org:prasant72/homemakers_commons.git'
      ref: master
      path: network_manager
  new_image_crop:
    git:
      url: 'https://github.com/prasant10050/image_crop_rotate_flip.git'
      ref: master
  open_file: ^3.3.2
  open_settings_plus: ^0.1.0
  palette_generator: ^0.3.3+2
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler:
    git:
      url: 'https://github.com/prasant10050/flutter-permission-handler.git'
      ref: master
      path: permission_handler
  phone_form_field:
    git:
      url: 'https://github.com/prasant10050/phone_form_field.git'
      ref: dev
#  phone_number:
#    git:
#      url: 'https://github.com/flutter-form-builder-ecosystem/phone_number.git'
  photo_view: ^0.14.0
  pinput:
    git:
      url: 'https://github.com/prasant10050/Flutter_Pinput.git'
      ref: master
  provider: ^6.0.5
  responsive_framework: ^1.1.0
  rxdart: ^0.27.7
  saver_gallery: ^2.0.1
  sembast: ^3.5.0+1
  sherlock:
    git:
      url: 'https://github.com/prasant10050/sherlock.git'
      ref: main
  sliver_tools: ^0.2.12
  synchronized: ^3.1.0
  timelines:
    git:
      url: 'https://github.com/prasant10050/timelines.git'
      ref: main
  transparent_image: ^2.0.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  visibility_detector: ^0.4.0+2
  wrap_and_more:
    git:
      url: 'https://github.com/prasant10050/wrap_and_more.git'
      ref: main

dev_dependencies:
  analyzer: ^4.4.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_gen_runner:
    git:
      url: 'https://github.com/FlutterGen/flutter_gen.git'
      ref: upgrade-renovate-flutter-3.x
      path: packages/runner
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  #go_router_builder: ^2.3.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  meta: ^1.9.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  analyzer: ^6.2.0
  http: ^1.0.0
  source_span: 1.9.1
  dom_tools: ^2.1.0
  markdown: ^4.0.1
  #meta: 1.7.0
  #image: ^3.1.3

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_native_splash:
  color: "#e65100"
  color_dark: "#e65100"
  background_image: "assets/image/homeway_logo.png"
  background_image_dark: "assets/image/homeway_logo.png"

  android_12:
    color: "#e65100"
    image: "assets/image/homeway_logo.png"
    icon_background_color: "#e65100"
    image_dark: "assets/image/homeway_logo.png"
    icon_background_color_dark: "#e65100"

  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/image/homeway_icon.png"
  image_path_ios: "assets/image/homeway_icon.png"
  image_path: "assets/image/homeway_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/homeway_icon.png"
    background_color: "#ffffff"
    theme_color: "#e65100"
  windows:
    generate: true
    image_path: "assets/image/homeway_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/homeway_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/image/
#    - assets/image/0.5x/
#    - assets/image/0.75x/
#    - assets/image/1.5x/
#    - assets/image/2.0x/
#    - assets/image/3.0x/
#    - assets/image/4.0x/
    - assets/svg/
    - assets/svg/flags/
    - google_fonts/
    - assets/lottie/
