name: homemakers_merchant
description: A app for HomeMakers merchant.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ac_connectivity:
    git:
      url: 'https://github.com/prasant10050/flutter-connectivity.git'
      ref: main
  animations: ^2.0.7
  app_links: ^3.4.3
  app_runner: ^2.2.0+1
  app_settings: ^4.2.0
  async: ^2.11.0
  back_button_interceptor: ^6.0.2
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.2
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  cross_file: ^0.3.3+4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  extended_image: ^8.0.2
  file_saver: ^0.2.5
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flex_color_scheme: ^7.1.2
  flex_seed_scheme: ^1.3.0
  flutter:
    sdk: flutter
  flutter_animarker: ^3.4.0-beta.1
  flutter_background_executor: ^1.0.0
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_libphonenumber: ^2.1.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_platform_widgets:
    git:
      url: 'https://github.com/prasant10050/flutter_platform_widgets.git'
      ref: master
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.2.0
  geocoder_buddy:
    git:
      url: 'https://github.com/prasant10050/geocoder_buddy.git'
      ref: main
  geolocator: ^9.0.2
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.3.1
  google_ml_kit: ^0.15.0
  google_mlkit_language_id: ^0.7.0
  google_mlkit_text_recognition: ^0.8.1
  google_mlkit_translation: ^0.7.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hyphenatorx: ^1.5.6+2
  image: ^4.0.17
  image_fade: ^0.6.2
  image_picker: ^1.0.0
  implicitly_animated_reorderable_list_2:
    git:
      url: 'https://github.com/prasant10050/implicitly_animated_reorderable_list_2.git'
      ref: master
  intl: ^0.18.0
  isolate_manager:
    git:
      url: 'https://github.com/prasant10050/isolate_manager.git'
      ref: main
  json_annotation: ^4.8.1
  location: ^4.4.0
  logger: ^1.4.0
  multi_image_crop:
    git:
      url: 'https://github.com/prasant10050/multi_image_crop.git'
      ref: master
  network_manager:
    git:
      url: 'git@bitbucket.org:prasant72/homemakers_commons.git'
      ref: master
      path: network_manager
  new_image_crop:
    git:
      url: 'https://github.com/prasant10050/image_crop_rotate_flip.git'
      ref: master
  open_settings_plus: ^0.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler:
    git:
      url: 'https://github.com/prasant10050/flutter-permission-handler.git'
      ref: master
      path: permission_handler
  phone_form_field:
    git:
      url: 'https://github.com/prasant10050/phone_form_field.git'
      ref: dev
  phone_number: ^2.0.1
  photo_view: ^0.14.0
  pinput:
    git:
      url: 'https://github.com/prasant10050/Flutter_Pinput.git'
      ref: master
  provider: ^6.0.5
  responsive_framework: ^1.1.0
  rxdart: ^0.27.7
  saver_gallery: ^2.0.1
  synchronized: ^3.1.0
  timelines:
    git:
      url: 'https://github.com/prasant10050/timelines.git'
      ref: main
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_gen_runner:
    git:
      url: 'https://github.com/FlutterGen/flutter_gen.git'
      ref: upgrade-renovate-flutter-3.x
      path: packages/runner
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  go_router_builder: ^2.2.0
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  http: ^1.0.0
  google_mlkit_text_recognition: ^0.8.1
  source_span: 1.9.1
  dom_tools: ^2.1.0
  markdown: ^4.0.1
  #image: ^3.1.3

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter_native_splash:
  color: "#ffffff"
  background_image: assets/image/splash.png
  background_image_dark: assets/image/splash.png

  android_12:
    color: "#ffffff"
    image: assets/image/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/image/splash.png
    icon_background_color_dark: "#ffffff"

  web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/
#    - assets/image/0.5x/
#    - assets/image/0.75x/
#    - assets/image/1.5x/
#    - assets/image/2.0x/
#    - assets/image/3.0x/
#    - assets/image/4.0x/
    - assets/svg/
    - assets/svg/flags/
