include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    argument_type_not_assignable: ignore
linter:
  rules:
    file_names: false
    argument_type_not_assignable: false
    public_member_api_docs: false
    omit_local_variable_types: false
    directives_ordering:

