name: network_manager
description: HomeMakers network manager package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  ac_connectivity:
    git:
      url: 'https://github.com/prasant10050/flutter-connectivity.git'
      ref: main
  collection: ^1.18.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  get_it_mixin: ^4.2.2
  json_annotation: ^4.8.1
  logger:
    git:
      url: 'https://github.com/prasant10050/logger.git'
      ref: master
  lottie: ^3.0.0
  path_provider: ^2.1.2
  retry: ^3.1.2
  sembast: ^3.6.0
  sembast_web: ^2.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^5.1.0

dependency_overrides:
  analyzer: ^5.13.0

flutter:
  assets:
    - assets/lottie/
