name: network_manager
description: HomeMakers network manager package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  ac_connectivity:
    git:
      url: 'https://github.com/prasant10050/flutter-connectivity.git'
      ref: main
  collection: ^1.18.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  get_it_mixin: ^4.2.2
  logger:
    git:
      url: 'https://github.com/prasant10050/logger.git'
      ref: master
  lottie: ^2.5.0
  path_provider: ^2.1.2
  retry: ^3.1.2
  sembast: ^3.5.0+1
  sembast_web: ^2.1.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/lottie/
