// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyHz8mM-VyxjewEq2qHPAyf9QvvAEPHA',
    appId: '1:564821867293:web:e7a68d2bfafea1494dfff4',
    messagingSenderId: '564821867293',
    projectId: 'homeway-e4577',
    authDomain: 'homeway-e4577.firebaseapp.com',
    databaseURL:
        'https://homeway-e4577-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeway-e4577.appspot.com',
    measurementId: 'G-YGFBHRMB8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HStMebYjnsg-F-4Zm2n_3bZ7P1b6-80',
    appId: '1:564821867293:android:9c1bf44aa79e09304dfff4',
    messagingSenderId: '564821867293',
    projectId: 'homeway-e4577',
    databaseURL:
        'https://homeway-e4577-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeway-e4577.appspot.com',
    androidClientId:
        '564821867293-ld4lkl9vmq0tfjhlpcvc5h8lh8p7thau.apps.googleusercontent.com',
    iosClientId:
        '564821867293-eloqhcbn6386lsd7lsps3847tli5o5ps.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.dev',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDirtZbG39mMswEYwdP4oqqkVjFv3KI5E',
    appId: '1:564821867293:ios:3bcfb98c0b906d594dfff4',
    messagingSenderId: '564821867293',
    projectId: 'homeway-e4577',
    databaseURL:
        'https://homeway-e4577-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeway-e4577.appspot.com',
    // 564821867293-ld4lkl9vmq0tfjhlpcvc5h8lh8p7thau.apps.googleusercontent.com - com.homemakers.merchant.dev
    // 564821867293-g5pmkrkhicsfl2do8pfp68lf9ei5e4rg.apps.googleusercontent.com - com.homemakers.merchant
    androidClientId:
        '564821867293-ld4lkl9vmq0tfjhlpcvc5h8lh8p7thau.apps.googleusercontent.com',
    iosClientId:
        '564821867293-eloqhcbn6386lsd7lsps3847tli5o5ps.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDirtZbG39mMswEYwdP4oqqkVjFv3KI5E',
    appId: '1:564821867293:ios:e8bc12a064b256ef4dfff4',
    messagingSenderId: '564821867293',
    projectId: 'homeway-e4577',
    databaseURL:
        'https://homeway-e4577-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeway-e4577.appspot.com',
    androidClientId:
        '564821867293-ld4lkl9vmq0tfjhlpcvc5h8lh8p7thau.apps.googleusercontent.com',
    iosClientId:
        '564821867293-qj14ngeun3ps623ihfovsloe1lsjia4e.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.homemakersMerchant.RunnerTests',
  );
}
