// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXy40wIpdr42vZDdcvclRriArmchJRer0',
    appId: '1:900157556438:web:8c012c482f9c82a6ae6b77',
    messagingSenderId: '900157556438',
    projectId: 'homemakers-merchant-dev',
    authDomain: 'homemakers-merchant-dev.firebaseapp.com',
    databaseURL:
        'https://homemakers-merchant-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-dev.appspot.com',
    measurementId: 'G-QZTW0YLH5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrisq6_kMGhDmcjECnNJXk2clI00MeDME',
    appId: '1:900157556438:android:235296fce3ebf2fdae6b77',
    messagingSenderId: '900157556438',
    projectId: 'homemakers-merchant-dev',
    databaseURL:
        'https://homemakers-merchant-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1vpTyvc71363WeATJNwVFODaVAsz3nH0',
    appId: '1:900157556438:ios:8a6de16ee8c78330ae6b77',
    messagingSenderId: '900157556438',
    projectId: 'homemakers-merchant-dev',
    databaseURL:
        'https://homemakers-merchant-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-dev.appspot.com',
    iosClientId:
        '900157556438-rs1s5ff598k0ap71v7ttf7ncts1qmiur.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1vpTyvc71363WeATJNwVFODaVAsz3nH0',
    appId: '1:900157556438:ios:c48a78e4d0364d44ae6b77',
    messagingSenderId: '900157556438',
    projectId: 'homemakers-merchant-dev',
    databaseURL:
        'https://homemakers-merchant-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-dev.appspot.com',
    iosClientId:
        '900157556438-pr00jphes2id1lgm4l95akcterq3fni8.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.RunnerTests.dev',
  );
}
