// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1z3CKl8YPI854oR6JTktD3EBXXedCIA',
    appId: '1:297962461340:web:619027412a717164907559',
    messagingSenderId: '297962461340',
    projectId: 'homemakers-merchant-prod',
    authDomain: 'homemakers-merchant-prod.firebaseapp.com',
    databaseURL:
        'https://homemakers-merchant-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-prod.appspot.com',
    measurementId: 'G-TTRN4GP630',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsshYbCGvkVfdzBcfME7GfAXwTTqQh60A',
    appId: '1:297962461340:android:ee371866e177d3d5907559',
    messagingSenderId: '297962461340',
    projectId: 'homemakers-merchant-prod',
    databaseURL:
        'https://homemakers-merchant-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwx8hQ4DwQgB8UD56erF7UDs_Pkgvrag',
    appId: '1:297962461340:ios:cd5c6d90237155f9907559',
    messagingSenderId: '297962461340',
    projectId: 'homemakers-merchant-prod',
    databaseURL:
        'https://homemakers-merchant-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-prod.appspot.com',
    iosClientId:
        '297962461340-vuf56s5rp31slf2a72n0cmjqrtg4ptd1.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwx8hQ4DwQgB8UD56erF7UDs_Pkgvrag',
    appId: '1:297962461340:ios:50f87be0d3f7487c907559',
    messagingSenderId: '297962461340',
    projectId: 'homemakers-merchant-prod',
    databaseURL:
        'https://homemakers-merchant-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homemakers-merchant-prod.appspot.com',
    iosClientId:
        '297962461340-eg5c9bjk88s09bbnaqq9alglhtpbrd77.apps.googleusercontent.com',
    iosBundleId: 'com.homemakers.merchant.RunnerTests.prod',
  );
}
