import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:file_picker/file_picker.dart';
import 'package:file_selector/file_selector.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/scheduler.dart';
import 'package:go_router/go_router.dart';
import 'package:homemakers_merchant/app/features/chat/domain/entities/chat_types_entity.dart';
import 'package:homemakers_merchant/app/features/chat/presentation/pages/chat_ui/chat_ui.dart';
import 'package:homemakers_merchant/app/features/chat/presentation/pages/login.dart';
import 'package:homemakers_merchant/app/features/common/index.dart';
import 'package:homemakers_merchant/app/features/dashboard/index.dart';
import 'package:homemakers_merchant/app/features/onboarding/presentation/pages/splash_page.dart';
import 'package:homemakers_merchant/base/widget_view.dart';
import 'package:homemakers_merchant/bootup/injection_container.dart';
import 'package:homemakers_merchant/config/translation/language_controller.dart';
import 'package:homemakers_merchant/config/translation/widgets/language_selection_widget.dart';
import 'package:homemakers_merchant/core/constants/global_app_constants.dart';
import 'package:homemakers_merchant/core/extensions/app_extension.dart';
import 'package:homemakers_merchant/core/extensions/global_extensions/dart_extensions.dart';
import 'package:homemakers_merchant/core/extensions/global_extensions/src/object.dart';
import 'package:homemakers_merchant/core/extensions/global_extensions/src/random.dart';
import 'package:homemakers_merchant/core/service/connectivity_bloc/src/connectivity_bloc/connectivity_service.dart';
import 'package:homemakers_merchant/shared/router/app_pages.dart';
import 'package:homemakers_merchant/shared/widgets/app/page_body.dart';
import 'package:homemakers_merchant/shared/widgets/universal/advanced_avatar/advanced_avatar.dart';
import 'package:homemakers_merchant/shared/widgets/universal/animate_do/animate_do.dart';
import 'package:homemakers_merchant/shared/widgets/universal/animated_gap/gap.dart';
import 'package:homemakers_merchant/shared/widgets/universal/async_builder/async_builder.dart';
import 'package:homemakers_merchant/shared/widgets/universal/double_tap_exit/double_tap_to_exit.dart';
import 'package:homemakers_merchant/shared/widgets/universal/image_loader/image_helper.dart';
import 'package:homemakers_merchant/utils/app_log.dart';
import 'package:meta/meta.dart';
import 'dart:io';
import 'package:homemakers_merchant/app/features/chat/domain/entities/chat_types_entity.dart' as types;

import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:mime/mime.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:faker/faker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:ui';
import 'package:path/path.dart' as path;
import 'dart:math' as math;

import '../../../utils/image_type.dart';

part 'package:homemakers_merchant/app/features/chat/data/remote/data_sources/firebase_chat_core.dart';
part 'package:homemakers_merchant/app/features/chat/data/remote/data_sources/firebase_chat_core_config.dart';
part 'package:homemakers_merchant/app/features/chat/data/remote/data_sources/util.dart';
part 'package:homemakers_merchant/app/features/chat/presentation/pages/chat.dart';
part 'package:homemakers_merchant/app/features/chat/presentation/pages/register.dart';
part 'package:homemakers_merchant/app/features/chat/presentation/pages/rooms.dart';
part 'package:homemakers_merchant/app/features/chat/presentation/pages/users.dart';
part 'package:homemakers_merchant/app/features/chat/presentation/pages/util.dart';
