// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';
import 'package:homemakers_merchant/app/features/address/domain/entities/address_model.dart';
import 'package:homemakers_merchant/app/shared/const/hive_type_constant.dart';
import 'package:network_manager/network_manager.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';

part 'user_model.g.dart';

@HiveType(typeId: HiveTypeConstant.userModel)
@JsonSerializable(explicitToJson: true)
@unfreezed
class UserModel extends INetworkModel<UserModel> with _$UserModel {
  @JsonSerializable(explicitToJson: true)
  factory UserModel({
    @HiveField(0) int? id,
    @HiveField(1) String? name,
    @HiveField(2) String? email,
    @HiveField(3) String? image,
    @HiveField(4) String? bio,
    @HiveField(5) String? token,
    @HiveField(6) String? address,
    @HiveField(7) String? latitude,
    @HiveField(8) String? longitude,
    @HiveField(9) @JsonKey(name: 'user_address') AddressModel? addressModel,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);

  @override
  UserModel fromJson(Map<String, dynamic> json) {
    return UserModel.fromJson(json);
  }

  //Map<String, dynamic> toJson() => _$UserModelToJson(this);

  @override
  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}
