// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:network_manager/network_manager.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'send_otp_response_model.g.dart';

@JsonSerializable(explicitToJson: true)
class SendOtpResponseModel extends INetworkModel<SendOtpResponseModel> {
  SendOtpResponseModel({
    this.appUserType,
    this.id,
  });
  factory SendOtpResponseModel.fromJson(Map<String, Object?> json) => _$SendOtpResponseModelFromJson(json);
  @JsonKey(name: 'id')
  String? id;
  @JsonKey(name: 'app_user_type')
  String? appUserType;
  @JsonKey(name: 'result')
  SendOtpResultModel? result;

  @override
  SendOtpResponseModel fromJson(Map<String, dynamic> json) {
    return SendOtpResponseModel.fromJson(json);
  }

  Map<String, dynamic> toMap() => _$SendOtpResponseModelToJson(this);
  @override
  Map<String, dynamic> toJson() => toMap();
}

@JsonSerializable(explicitToJson: true)
class SendOtpResultModel extends INetworkModel<SendOtpResultModel> {
  SendOtpResultModel({
    this.otp,
    this.message,
  });
  factory SendOtpResultModel.fromJson(Map<String, Object?> json) => _$SendOtpResultModelFromJson(json);
  @JsonKey(name: 'message')
  String? message;
  @JsonKey(name: 'otp')
  int? otp;

  @override
  SendOtpResultModel fromJson(Map<String, dynamic> json) {
    return SendOtpResultModel.fromJson(json);
  }

  Map<String, dynamic> toMap() => _$SendOtpResultModelToJson(this);
  @override
  Map<String, dynamic> toJson() => toMap();
}
