// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:network_manager/network_manager.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'send_otp_response_model.g.dart';

@JsonSerializable(explicitToJson: true)
class SendOtpResponseModel extends INetworkModel<SendOtpResponseModel> {
  SendOtpResponseModel({
    this.appUserType,
    this.message,
  });
  factory SendOtpResponseModel.fromJson(Map<String, Object?> json) =>
      _$SendOtpResponseModelFromJson(json);
  @JsonKey(name: 'message')
  String? message;
  @JsonKey(name: 'app_user_type')
  String? appUserType;

  @override
  SendOtpResponseModel fromMap(Map<String, dynamic> json) {
    return SendOtpResponseModel.fromJson(json);
  }

  Map<String, dynamic> toJson() => _$SendOtpResponseModelToJson(this);
  @override
  Map<String, dynamic> toMap() => toJson();
}
