// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:network_manager/network_manager.dart';

// required: associates our `main.dart` with the code generated by Freezed

part 'verify_otp_response_model.g.dart';

@JsonSerializable(explicitToJson: true)
class VerifyOtpResponseModel extends INetworkModel<VerifyOtpResponseModel> {
  VerifyOtpResponseModel({
    this.appUserType,
    this.message,
    this.currentStatus,
    this.userID,
    this.authToken,
  });
  factory VerifyOtpResponseModel.fromJson(Map<String, Object?> json) => _$VerifyOtpResponseModelFromJson(json);
  @JsonKey(name: 'message')
  String? message;
  @JsonKey(name: 'uid')
  String? userID;
  @JsonKey(name: 'access_token')
  String? authToken;
  @JsonKey(name: 'user_type')
  String? appUserType;
  @JsonKey(name: 'current_status')
  int? currentStatus;
  @override
  VerifyOtpResponseModel fromJson(Map<String, dynamic> json) {
    return VerifyOtpResponseModel.fromJson(json);
  }

  Map<String, dynamic> toMap() => _$VerifyOtpResponseModelToJson(this);
  @override
  Map<String, dynamic> toJson() => toMap();
}
